### ISSUE TITLE
Strange output

### ISSUE THREAD

**Issue by jorenham** [addisonElliott/polarTransform#3]
First of all, awesome project!
When I run the OpenCL code with

```c++
const float phi_from = 0.0, phi_to = 2 * M_PI;
const float theta_from = 0.5 * M_PI, theta_to = M_PI;
const int phi_steps = 400, theta_steps = 400;
unsigned char colors[3 * 3] = {255, 0, 0,
                               0, 255, 0,
                               0, 0, 255 };
const float friction = 0.1;
const int exponent = 2;
const unsigned int n_magnets = 3;
float alphas[n_magnets] = { 1.0, 1.0, 1.0 };
float rns[3 * n_magnets] = { -0.8660254, -0.5, -1.3,
                              0.8660254, -0.5, -1.3,
                              0.0, 1.0, -1.3 };
const float time_step = 5.0f;
const float min_kin = 0.5f;
const int max_iterations = 30;
```

I get the following output image (in <1s :tada: )

![output](https://user-images.githubusercontent.com/6208662/43049720-c45de092-8dfc-11e8-8c8e-83ab132504ca.png)

and I expected to get

![screenshot from 2018-07-22 22-16-08](https://user-images.githubusercontent.com/6208662/43049726-ef3e044a-8dfc-11e8-816d-1c6f846267fa.png)

which is from your slides.

Is there something wrong going on here or am I missing something?

**Comment by jorenham** [comment]
Woops wrong project

**Comment by addisonElliott** [comment]
Glad this repository is helping you out. If you don't mind, starring the repository helps a bunch!
