### ISSUE TITLE
maxRadius only uses first dimension

### ISSUE THREAD

**Issue by scott-trinkle** [addisonElliott/polarTransform#5]
In line 762 of polarTransform.py, the "corners" are scaled by 

`image.shape[0:1]`

This slicing selects only the first element of image.shape. It should be

`image.shape[0:2]`

**Comment by addisonElliott** [comment]
First of all, thanks for the issue. 

Line [762](https://github.com/addisonElliott/polarTransform/blob/master/polarTransform.py#L762) is the following line:
`        # Initial angle of zero if none is selected`

I believe you mean line [https://github.com/addisonElliott/polarTransform/blob/master/polarTransform.py#L762](755):
`        corners = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]) * image.shape[0:1]`

If you don't mind, can you submit a PR for this? Also, if possible, please write a test that fails before your fix and succeeds after your fix is applied. Apparently my tests did not do a good job of testing for that.

**Comment by scott-trinkle** [comment]
Correct, that's the line I was referencing. 

No problem! I'll work on it soon, glad to help.
